### ISSUE TITLE
improve ux for data creators

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/cell-feature-data#45]
Create a single validation script that a data creator can run to ensure integrity prior to attempting to upload a dataset.
`npm run validate-dataset [PATH_TO_DATASET]`

A second improvement for data creators would be to publish docs online (I feel like maybe we already do this but didn't check -- but improving documentation in general is the gist here)

**Comment by toloudis** [comment]
In particular we saw a bug with a mismatch between number of features in cell-feature-analysis.json and the featuresDataOrder in the dataset.json file.  This could / should be checked and reported by such a validation script.

**Comment by meganrm** [comment]
@toloudis if there is more progress on the drug dataset while I'm out of town, can you work with Ruge to make sure that any errors that exist in the input dataset are accurately caught by our "validate-dataset" script? 

Could also involve updating the docs or descriptions as well.
