### ISSUE TITLE
dataset.json userData/totalCells is required by CFE

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/cell-feature-data#73]
currently CFE crashes if you don't supply userData/totalCells. 
we should mark this as required for now or change CFE to make it optional at run-time.

**Comment by rugeli** [comment]
Could you explain further about how CFE crashes if we don't supply userData? I found the description for userData in `definitions.schema.json` as `"Optional display data"`, and it is not required anywhere. Should `userData` is already an optional?
I deleted the entire `userData` including `totalCells` in a single dataset's `dataset.json` file for testing, and it processed through. Let me know if I should look at something else for this issue, thanks!

**Comment by toloudis** [comment]
I'm referring to only the `totalCells` field inside of userData.  It does not crash anything in cell-feature-data, but when Cell Feature Explorer goes to use the data, if totalCells is undefined then the app crashes.  
So we have to either make that piece of data be required in cell-feature-data, or change Cell Feature Explorer so that it doesn't crash.

As you said, it processed through without problems. But if you try to load that dataset in the CFE app you will see it crash there.

**Comment by toloudis** [comment]
This is not really an immediate problem but for future datasets it could easily come up again.

**Comment by rugeli** [comment]
This issue is closed by PR#137 `make-userData-optional` in `cell-feature-explorer`
