### ISSUE TITLE
discrete features must have options

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/cell-feature-data#85]
## Use Case

CFE crashes if a discrete feature does not have options. 
I can make a change to CFE to use the index value as label (https://github.com/allen-cell-animated/cell-feature-explorer/pull/138) but extra option metadata would be missing.

## Acceptance Criteria

Validation should flag this?
Do the scripts currently auto-create options if they are not provided?

**Comment by meganrm** [comment]
yes validation should flag this: error out that says "discrete values need options, example:` [IN LINE EXAMPLE OF WHAT AN OPTION VALUE LOOKS LIKE]` [LINK TO DOCUMENTATION]"
