### ISSUE TITLE
idea: Python create_dataset script

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/cell-feature-data#91]
## Use Case

More tooling to help scientists set up data for CFE.  Goal is to make it simple: take in a spreadsheet of features, output a basic dataset.  it's ok if it's not fleshed out completely but it should validate.

## Acceptance Criteria

Python script that can be run from command line or invoked from other python code.
It should: 

- [x] - set up a dataset directory and create all necessary json files.  
- [x] - accept a spreadsheet of features (spec tbd but probably requires an "id" column, and the rest can be feature names
- [x] - automatically identify string-valued features and turn them into discrete features with options
- [x] - fill in feature defs (and all other json files) as best it can
- [x] - some basic validation, tell user if the spreadsheet results in bad data
- [ ] - accept csv file or pandas dataframe
- [x] - leave image processing to other code.  optionally fill in image names as placeholders
- [x] - bonus: provide an "interactive" mode that prompts for some data entry on command line (e.g. feature descriptions, units, some of the dataset.json fields, etc)

## Details

Must be Python so other scientists can import it

**Comment by meganrm** [comment]
a flow I could imagine:
1. `create-dataset -name [NAME]`
2. prompt for `version` 
3. prompt for `title` (optional)
4. prompt for `description`  (optional)
5. prompt for path to spreadsheet 
6. create a folder within `data` with the `name-version`
7. in the folder create `dataset.json`, `feature_defs.json`, `cell_feature_analysis.json`, and `image-settings.json`
8. For `feature_defs.json`: 
    *use string parsing to do a best guess as key/displayName (ie if the column names are capitalized with spaces, it's a displayName and create a key by replacing spaces with dashes and lowercase the letters)
    *check the data to determine if it's a discrete or continuous feature. If discrete, create the options mapping with some default colors. 
    * `description` is a blank string they can edit themselves later
    * `unit` is a blank string they edit themselves as well (if the column name has parenthesis you can put whatever was in between the parenthesis as the unit)
10. `images.json` would be blank 
11. if successful a log tells the user to run `enter-required-setting` to be prompted for all the additional required data. They can also just edit dataset.json manually themselves) 
12. prompt for `xAxis default` (must be one of the features in the feature refs, could be something they choose by up and down arrows)
13. prompt for `yAxis default`
14. prompt for `colorBy` 
15. prompt for `groupBy`
16. prompt for `thumbnailRoot`
17. prompt for `volumeViewerDataRoot`
18. prompt for `downloadRoot`

**Comment by meganrm** [comment]
@toloudis do you have an example spreadsheet we could use to test this out?

**Comment by toloudis** [comment]
I think it is up to us to define the spreadsheet spec, to be something that is very obvious and easy for a data creator to make.  I'd start with these columns: [cell id, feature_0_key, feature_1_key, ...] etc.    Then we have details like NaN, missing data, validation (string or number?).

Some other thoughts... 

I can't remember if images.json has a sensible non-empty default but at the very least it's good for grouping channels.  More advanced is you can set some volume viewer settings like color and even thresholding.

It would probably be good to think of create_dataset in a python processing pipeline in addition to the interactive command line mode.  It's very likely that the spreadsheet input will be created by python code and could be passed directly in to a function call.
Maybe the interactive mode of create-dataset should be able to edit an existing dataset.  So maybe you started with a python workflow that populated some feature values, and now you are ready to go in and refine some of the dataset.json parameters or flesh out the feature defs.

Anyway, it would be a good way to bootstrap a dataset and ensure that it's valid to begin with.
